apiVersion: v2
name       : helm-chart
description: Helm chart
type       : application
version    : 1.0.0   # This is the Helm Chart version
appVersion : "1.2.3" # This is the version of the application being deployed
