server:
  port: 8082

spring:
  application:
    name: notification
  datasource:
    url: jdbc:h2:mem:${DB_NAME:noticedb}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}

logging:
  level:
    web: debug