server:
  port: 8080

spring:
  application:
    name: order
  datasource:
    url: jdbc:h2:mem:${DB_NAME:orderdb}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false

  kafka:
    bootstrap-servers: ${KAFKA_BROKER_LIST}

rest-client:
  billing-base-url: ${BILLING_BASE_URL}

logging:
  level:
    web: debug
