apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc-billing
spec:
  selector:
    env: billing
  ports:
    - protocol  : {{ .Values.ports.protocol }}
      port      : {{ .Values.ports.port }}
      targetPort: {{ .Values.container.billing.containerPort }}
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc-notice
spec:
  selector:
    env: notice
  ports:
    - protocol  : {{ .Values.ports.protocol }}
      port      : {{ .Values.ports.port }}
      targetPort: {{ .Values.container.notice.containerPort }}
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc-order
spec:
  selector:
    env: order
  ports:
    - protocol  : {{ .Values.ports.protocol }}
      port      : {{ .Values.ports.port }}
      targetPort: {{ .Values.container.order.containerPort }}
  type: ClusterIP
