server:
  port: 8081

spring:
  application:
    name: billing
  datasource:
    url: jdbc:h2:mem:${DB_NAME:billingdb}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false


